CREATE TABLE ITEMS( ITEM_I SERIAL, SKU TEXT NOT NULL, ITEM_DESCRIPTION TEXT DEFAULT NULL, PRICE NUMERIC (10,5), CRTE_TS TIMESTAMPTZ NULL DEFAULT current_timestamp);

drop TABLE ITEMS;

select * from items;

delete from items;

